events { worker_connections 1024; }

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # Docker internal DNS
    resolver 127.0.0.11 valid=30s ipv6=off;

    server {
        listen 80;
        server_name localhost;

        # healthcheck
        location /healthz {
            return 200 '{"status":"ok","service":"api-gateway"}';
            add_header Content-Type application/json;
        }

        # 1. Auth Service
        location /api/auth/ {
            set $user_svc http://user-service:8000;
            proxy_pass $user_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 2. Catalog Service
        location /api/catalog/ {
            set $catalog_svc http://catalog-service:8000;
            proxy_pass $catalog_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 10M;
        }

        # 3. Cart Service
        location /api/cart {
            set $cart_svc http://cart-service:8000;
            proxy_pass $cart_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 4. Order Service
        location /api/orders {
            set $order_svc http://order-service:8000;
            proxy_pass $order_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 5. Payments (doing viec sang Order & Payment Service)
        location /api/payments/ {
            set $payment_svc http://order-service:8000;
            proxy_pass $payment_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
